---
# Headless service for StatefulSet
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: app-project-management
  labels:
    app: redis
spec:
  clusterIP: None
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
      name: redis
---
# ClusterIP for app connections
apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  namespace: app-project-management
  labels:
    app: redis
spec:
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
      name: redis
