apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: project-management-secrets
  namespace: app-project-management
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: project-management-secrets   # K8s Secret name that gets created
    creationPolicy: Owner
  data:
    - secretKey: MONGO_ROOT_USER
      remoteRef:
        key: project-management/dev    # AWS Secrets Manager secret name (overridden per env via Kustomize)
        property: MONGO_ROOT_USER
    - secretKey: MONGO_ROOT_PASSWORD
      remoteRef:
        key: project-management/dev
        property: MONGO_ROOT_PASSWORD
    - secretKey: MONGO_DB
      remoteRef:
        key: project-management/dev
        property: MONGO_DB
    - secretKey: JWT_SECRET
      remoteRef:
        key: project-management/dev
        property: JWT_SECRET
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: project-management/dev
        property: REDIS_PASSWORD
