apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: app-project-management

resources:
  - external-secrets/
  - mongodb/
  - redis/
  - server/
  - client/

# Common labels applied to every resource
commonLabels:
  app.kubernetes.io/part-of: project-management
  app.kubernetes.io/managed-by: argocd
