apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.io
spec:
  project: platform
  source:
    repoURL: public.ecr.aws/karpenter
    chart: karpenter
    targetRevision: "0.37.*"
    helm:
      values: |
        serviceAccount:
          annotations:
            eks.amazonaws.com/role-arn: KARPENTER_ROLE_ARN  # replaced by CI
        settings:
          clusterName: CLUSTER_NAME                         # replaced by CI
  destination:
    server: https://kubernetes.default.svc
    namespace: karpenter
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
